sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start creating an image with dockerfile..."
  - docker build -t annahxxl/react-docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true annahxxl/react-docker-app npm run test -- --coverage

after_success:
  - echo "Test success!"
